FROM rust:1.86.0-slim

WORKDIR /app

# Install cargo-watch
RUN cargo install cargo-watch

# Copy your full source code
COPY . .

# Expose your app port
EXPOSE 8080

# Start cargo-watch to recompile and run on file changes
CMD ["cargo", "watch", "-x", "run"]
